# If the commands should be registered to act like WorldEdit commands (ex: "//pos1" vs "/se pos1"
world-edit-commands: true

# The material used as a selection wand
wand-material: "wood axe"
# If the wand can only be used in creative mode
creative-only-wand: true

# The number of blocks that may be affected by any action per tick
affected-blocks-per-tick: 3000

# The number of ticks between the drawing of a selection outline
outline-update-rate: 10