main: "io.github.mrsperry.simpleedit.SimpleEdit"
name: "SimpleEdit"
version: ${project.version}
api-version: 1.16
commands:
  simpleedit:
    description: "All encompassing command for SimpleEdit"
    usage: "/simpleedit <action | help>"
    aliases: [ "se" ]